"""Every custom emoji is an application emoji the bot owns (plans/app-emoji-migration.md).

The manifest (clashcontrol/icons/emoji_manifest.json) lists each icon; the generator
(activity/client/scripts/build-emoji-assets.mjs) turns its master into a lossless square WebP;
the bot uploads missing ones and resolves BotEmojis attributes to them at lookup time, keeping the
old guild-emoji ids as fallbacks.
"""
from __future__ import annotations

import os
import re
from unittest.mock import AsyncMock, MagicMock

import pytest

_UPPER_ATTR = re.compile(r"^[A-Z][A-Z0-9_]*$")
_NAME_RULE = re.compile(r"^\w{2,32}$")  # Discord: >= 2 chars, alphanumerics and underscores


@pytest.fixture(autouse=True)
def _isolated_resolution():
    import clashcontrol.emojis as emojis

    saved = dict(emojis._resolved)
    emojis._resolved.clear()
    yield
    emojis._resolved.clear()
    emojis._resolved.update(saved)


def _botemoji_attrs() -> set[str]:
    from clashcontrol.emojis import BotEmojis

    return {name for name in vars(BotEmojis) if _UPPER_ATTR.match(name)}


def _emoji(name: str, emoji_id: int) -> MagicMock:
    emoji = MagicMock()
    emoji.name = name
    emoji.id = emoji_id
    emoji.__str__ = lambda self: f"<:{name}:{emoji_id}>"  # type: ignore[assignment]
    return emoji


# ---------------------------------------------------------------------------
# Manifest <-> BotEmojis <-> files
# ---------------------------------------------------------------------------

def test_manifest_and_botemojis_cover_each_other_exactly():
    """A BotEmojis constant without a manifest entry would never become an application emoji; a
    manifest entry without a constant would be uploaded but unreachable from the code."""
    from clashcontrol.emojis import load_emoji_manifest

    manifest_attrs = {entry["attr"] for entry in load_emoji_manifest()}
    assert manifest_attrs == _botemoji_attrs()


def test_manifest_names_are_valid_and_unique():
    from clashcontrol.emojis import load_emoji_manifest

    names = [entry["name"] for entry in load_emoji_manifest()]
    assert len(names) == len(set(names))
    for name in names:
        assert _NAME_RULE.match(name), name


def test_every_manifest_master_exists():
    from clashcontrol.emojis import load_emoji_manifest

    icons = os.path.join("clashcontrol", "icons")
    for entry in load_emoji_manifest():
        assert os.path.exists(os.path.join(icons, entry["source"])), entry


def test_every_upload_file_is_square_lossless_webp_under_the_limit():
    """Generated by build-emoji-assets.mjs and committed. Lossless matters: lossy WebP smears the
    thin edges these small icons are made of. Read straight from the VP8L header, no Pillow."""
    from clashcontrol.emojis import emoji_asset_path, load_emoji_manifest

    for entry in load_emoji_manifest():
        path = emoji_asset_path(entry["name"])
        assert os.path.exists(path), f"missing {path} — run `npm run build:emoji` in activity/client"
        data = open(path, "rb").read()
        assert len(data) <= 256 * 1024, f"{entry['name']}: over Discord's 256 KiB limit"
        assert data[0:4] == b"RIFF" and data[8:12] == b"WEBP", entry["name"]
        assert data[12:16] == b"VP8L", f"{entry['name']}: not LOSSLESS WebP"
        bits = int.from_bytes(data[21:25], "little")
        width, height = (bits & 0x3FFF) + 1, ((bits >> 14) & 0x3FFF) + 1
        assert width == height, f"{entry['name']}: {width}x{height} is not square"
        assert width <= 128, f"{entry['name']}: {width}px exceeds Discord's 128px emoji size"


# ---------------------------------------------------------------------------
# Lookup-time resolution with fallback
# ---------------------------------------------------------------------------

def test_attributes_fall_back_to_the_guild_emoji_until_resolved():
    from clashcontrol.emojis import BotEmojis

    assert BotEmojis.ENABLED == "<:enabled:1455513859715629076>"
    assert getattr(BotEmojis, "TH05", None) == "<:TH05:1470128740309667850>"


def test_resolved_application_emoji_wins_for_every_access_style():
    import clashcontrol.emojis as emojis
    from clashcontrol.emojis import BotEmojis, th_icon_url

    emojis._resolved["TH05"] = "<:TH05:1552060584176914599>"

    assert BotEmojis.TH05 == "<:TH05:1552060584176914599>"
    assert getattr(BotEmojis, "TH05", "x") == "<:TH05:1552060584176914599>"
    assert getattr(BotEmojis, "TH99", "default") == "default"
    # The Activity's TH icons follow automatically — the CDN serves application emojis by id too.
    assert th_icon_url(5) == "https://cdn.discordapp.com/emojis/1552060584176914599.png"


# ---------------------------------------------------------------------------
# ensure_application_emojis
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_already_uploaded_emojis_are_resolved_without_uploading():
    import clashcontrol.emojis as emojis
    from clashcontrol.emojis import BotEmojis, load_emoji_manifest

    manifest = load_emoji_manifest()
    bot = MagicMock()
    bot.fetch_application_emojis = AsyncMock(return_value=[
        _emoji(entry["name"], 1552060584176914000 + i) for i, entry in enumerate(manifest)
    ])
    bot.create_application_emoji = AsyncMock()

    resolved = await emojis.ensure_application_emojis(bot, background=False)

    assert resolved == len(manifest)
    bot.create_application_emoji.assert_not_awaited()
    assert BotEmojis.ENABLED.startswith("<:enabled:1552060584176914")


@pytest.mark.asyncio
async def test_only_missing_emojis_are_uploaded_from_their_webp(monkeypatch):
    import clashcontrol.emojis as emojis
    from clashcontrol.emojis import BotEmojis, load_emoji_manifest

    monkeypatch.setattr(emojis, "UPLOAD_PACING_SECONDS", 0)
    manifest = load_emoji_manifest()
    present = [e for e in manifest if e["name"] != "cwl_bench"]

    bot = MagicMock()
    bot.fetch_application_emojis = AsyncMock(return_value=[
        _emoji(e["name"], 1552060584176914000 + i) for i, e in enumerate(present)
    ])
    bot.create_application_emoji = AsyncMock(return_value=_emoji("cwl_bench", 1552060584176914515))

    await emojis.ensure_application_emojis(bot, background=False)

    bot.create_application_emoji.assert_awaited_once()
    kwargs = bot.create_application_emoji.await_args.kwargs
    assert kwargs["name"] == "cwl_bench"
    assert kwargs["image"][0:4] == b"RIFF" and kwargs["image"][8:12] == b"WEBP"
    assert BotEmojis.CWL_BENCH == "<:cwl_bench:1552060584176914515>"


@pytest.mark.asyncio
async def test_a_first_start_uploads_in_the_background_without_blocking(monkeypatch):
    """~34 uploads on the first start must never hold up the boot sequence."""
    import sys

    import clashcontrol.emojis as emojis

    spawned = []
    fake_qbcore = MagicMock()
    fake_qbcore.spawn_tracked = MagicMock(side_effect=lambda name, coro: spawned.append((name, coro)))
    monkeypatch.setitem(sys.modules, "QBcore", fake_qbcore)

    bot = MagicMock()
    bot.fetch_application_emojis = AsyncMock(return_value=[])
    bot.create_application_emoji = AsyncMock()

    resolved = await emojis.ensure_application_emojis(bot)

    assert resolved == 0
    assert len(spawned) == 1 and spawned[0][0] == "upload-application-emojis"
    bot.create_application_emoji.assert_not_awaited()  # nothing uploaded inline
    spawned[0][1].close()  # don't leave the never-awaited coroutine behind


@pytest.mark.asyncio
async def test_one_failed_upload_does_not_stop_the_rest(monkeypatch):
    import clashcontrol.emojis as emojis
    from clashcontrol.emojis import BotEmojis

    monkeypatch.setattr(emojis, "UPLOAD_PACING_SECONDS", 0)
    calls = {"n": 0}

    async def flaky(name, image):
        calls["n"] += 1
        if name == "enabled":
            raise RuntimeError("Discord rejected it")
        return _emoji(name, 1552060584176915000 + calls["n"])

    bot = MagicMock()
    bot.fetch_application_emojis = AsyncMock(return_value=[])
    bot.create_application_emoji = AsyncMock(side_effect=flaky)

    await emojis.ensure_application_emojis(bot, background=False)

    assert BotEmojis.ENABLED == "<:enabled:1455513859715629076>"  # kept its fallback
    assert BotEmojis.DISABLED.startswith("<:disabled:155206058417691")  # the rest went through


@pytest.mark.asyncio
async def test_discord_unreachable_keeps_every_fallback():
    import clashcontrol.emojis as emojis
    from clashcontrol.emojis import BotEmojis

    bot = MagicMock()
    bot.fetch_application_emojis = AsyncMock(side_effect=RuntimeError("Discord is having a day"))

    assert await emojis.ensure_application_emojis(bot) == 0
    assert BotEmojis.ENABLED == "<:enabled:1455513859715629076>"
    assert BotEmojis.CWL_BENCH == "\U0001fa91"


# ---------------------------------------------------------------------------
# No hardcoded emoji ids outside BotEmojis
# ---------------------------------------------------------------------------

_MARKUP = re.compile(r"<a?:\w+:\d{15,20}>")


def test_no_translation_string_hardcodes_an_emoji_id():
    """2026-09-23: two role-configuration strings carried '<:gcheck:…>' / '<:verified:…>' inline,
    so that screen kept showing the old SERVER emoji after every other icon moved to the
    application emoji. Icons must come from BotEmojis through a placeholder such as {emoji}."""
    import glob
    import json

    for path in glob.glob("clashcontrol/translations/*.json"):
        data = json.load(open(path, encoding="utf-8"))

        def walk(node, trail=""):
            if isinstance(node, dict):
                for key, value in node.items():
                    walk(value, f"{trail}.{key}" if trail else key)
            elif isinstance(node, str):
                assert not _MARKUP.search(node), f"{path}: {trail} hardcodes an emoji id"

        walk(data)


def test_no_python_module_hardcodes_an_emoji_id_outside_emojis_py():
    import glob

    for path in glob.glob("clashcontrol/**/*.py", recursive=True) + glob.glob("*.py"):
        if path.replace("\\", "/").endswith("clashcontrol/emojis.py"):
            continue
        source = open(path, encoding="utf-8").read()
        assert not _MARKUP.search(source), f"{path} hardcodes an emoji id — use BotEmojis"


def test_role_assignment_mode_line_uses_the_resolved_emoji():
    import clashcontrol.emojis as emojis
    from clashcontrol.i18n import t

    emojis._resolved["GCHECK"] = "<:gcheck:1552060584176914601>"
    line = t('ui_components.role_configuration.assignment_mode_simple', guild_id=None,
             emoji=emojis.BotEmojis.GCHECK)
    assert line.startswith("<:gcheck:1552060584176914601>")
